# Generated by Django 6.0.7 on 2026-08-01 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footwear',
            fields=[
                ('sku_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('cost', models.FloatField(default=0.0)),
                ('stock', models.IntegerField(default=0)),
                ('min_stock', models.IntegerField(default=10)),
                ('sizes', models.JSONField(default=list)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('rating', models.FloatField(default=4.8)),
                ('reviews_count', models.IntegerField(default=50)),
                ('image', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('sales_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('invoice_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('customer_email', models.CharField(blank=True, max_length=150)),
                ('date', models.CharField(max_length=100)),
                ('subtotal', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0)),
                ('discount_amount', models.FloatField(default=0.0)),
                ('tax', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('payment_method', models.CharField(default='Credit Card', max_length=50)),
                ('status', models.CharField(default='Completed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footwear_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField(default=0.0)),
                ('qty', models.IntegerField(default=1)),
                ('size', models.IntegerField(default=9)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
            ],
        ),
    ]
